### ISSUE TITLE
CalledCount

### ISSUE THREAD

**Issue by davidbarton** [BaseCase/testdouble-chai#9]
Hi I would like to have `calledCount` method available. I did try to make PR but got lost in all those arguments. It would have been working like this

```
it("can tell you if a testdouble object was called an exact amount of times", function() {
  var td = testdouble.function();
  td("hi");
  expect(td).to.have.been.calledCount(1);
});
```

**Comment by BaseCase** [comment]
Hi @davidbarton, thanks for the suggestion! I believe this overlaps with #8, so I'll close this one and take it as a reminder that I need to do some enhancements on this library :)
